name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          cache: maven
          distribution: 'temurin'
      - name: Test with Maven
        run: mvn --batch-mode --file pom.xml package