name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          cache: maven
          distribution: 'adopt'
      - name: Verify Maven version
        run: mvn --version
      - name: Test with Maven
        run: mvn --batch-mode test --file pom.xml